.TH "asm" "v1"
.SH NOM
asm
.SH SYNOPSIS
USAGE:
.br
    ./asm file_name[.s]
.SH DESCRIPTION
file_name file in assembly language to be converted into file_name.cor, an
executable in the Virtual Machine.
.SH REPORTING BUG
There is no bug
.SH COPYRIGHT
© ASM-Studios. All rights reserved.
.SH AUTHOR
Axel CHYPRE
.br
Yohann MANGENOT
.br
Mael RABOT
.br
Mathieu BOREL
.SH SEE ALSO
corewar(v1)
